### ISSUE TITLE
The project is not known to public anymore

### ISSUE THREAD

**Issue by shamansir** [himselfv/wakan#294]
That is not an issue per se, but I haven't found any other way to tell that. I've used the Wakan software long long ago to create the reference of Japanese Language in Russian (who cares, but still), and it was the awesome experience. I'm sure it's even much better now, can't try it since nowadays I'm on Mac and also don't do any Japanese at that point of time, but probably I could find the ways to run it anyway.

The official site is not opening for a long time, at least for me—I've tried to find your software again several times through years. And only now, through Reddit post, I discovered that you still develop it and keep it alive. Please, if you have a stable version to show, resurrect the website and help users to find it as they were able before.

**Comment by Stiles-X** [comment]
https://www.reddit.com/r/LearnJapanese/comments/3apo45/japanese_subtitles_with_furigana_for_anime/
directed me to Wakan here. Not all hope is lost.

**Comment by himselfv** [comment]
The official site is by the original developer who doesn't work on this any more, I think. Thankfully, they've generously open-sourced it so this version is now here.
