### ISSUE TITLE
Can't start in Portable mode even though directory should be writable.

### ISSUE THREAD

**Issue by zblesk** [himselfv/wakan#297]
I'm running the newest version downloadable today (did a fresh install), on Windows 10. 
I'm trying to get it to run in Portable mode.
After installing, I've set the Install var to Portable.

The current contents of my `wakan.ini`: 

```ini
[General]
Install=Portable

[Language]
LNGFile=en.lng
```

The Language section was added by the application when it started (and asked for language), so the ini clearly is writable. 
I've made sure my user has Full Control rights over the directory and files. I've tried explicitly adding the permissions and overwriting all childs' perms to make sure. 
I've tried copying the entire Wakan dir to a different location and running from there. 
I've checked the folder's properties and made sure the files aren't Read Only. 
I've tried starting Wakan as admin. 

Always this same error:

![image](https://user-images.githubusercontent.com/4245227/118488943-8c8dc280-b71c-11eb-9c7b-ecc4142a1827.png)

What can I do to fix this? Or is there a workaround (like creating the required files manually and letting Wakan overwrite them)? 
Is there some error log, or something? There seems to be nothing in the install dir.

Thank you.

**Comment by himselfv** [comment]
Create a UserData\ subfolder in Wakan folder and try again. Fixed this for the next version, thanks for notifying!

**Comment by zblesk** [comment]
That fixed it! Thanks for your quick answer.
