### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hellishvictor** [himselfv/wakan#299]
Hi, the program stores data on the registry key **HKEY_CURRENT_USER\Software\Labyrinth**, and it would be awesome if instead that were stored on an file.ini on the same folder where the program is installed (and also have the option to keep the file **wakan.usr** on **\AppData\Roaming\Wakan\**, were it used to be located), so it can be use as portable and leave no trace behind.

Cheers.

**Comment by himselfv** [comment]
It's already like that: https://github.com/himselfv/wakan/blob/master/Docs/Portable.md

Either edit wakan.ini and set:
```
[General]
Install=Portable
```

Or just delete it and Wakan will ask you on the next start.

**Comment by hellishvictor** [comment]
Awesome, you rule man!
Cheers.
